
# Título e descrição do site - SEO
title: Jekyll para designers
description: Site experimental para aprender Jekyll


# Para que as páginas não tenham ".html" no browser
permalink: pretty


# Pastas e ficheiros que não queremos incluir no site final
exclude: ['config.codekit','README.md','_less','_site']

